services:
  - type: web
    name: aminuite-api # Render 대시보드의 서비스 이름과 일치
    runtime: java     # <--- 'env: java' 대신 또는 함께 'runtime: java' 명시
    region: singapore # 실제 설정한 지역
    plan: free
    branch: main
    buildFilter: # 이 부분은 빌드 시간을 줄이기 위해 추가하는 것이 좋습니다.
      paths:
        - "src/**"
        - "build.gradle"
        - "settings.gradle" # Gradle 설정 파일
        - "gradlew"
        - "gradlew.bat"
        - "gradle/**"
      # - "pom.xml" # Maven 사용 시
    buildCommand: "./gradlew build -x test"
    startCommand: "java -jar build/libs/political-chat-backend-0.0.1-SNAPSHOT.jar" # <<--- 실제 JAR 파일명!
    envVars:
      - key: JAVA_VERSION
        value: 21
      # 다른 환경 변수들 (DB, JWT_SECRET)은 Render 대시보드에서 설정한 값을 사용하도록
      # 여기서는 명시하지 않거나, sync: false 옵션과 함께 값을 지정할 수 있습니다.
      # 예시:
      # - key: DB_URL
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false